package com.example.prectical2.utils

const val MAIN_SCR_ROUTE = "MAIN_SCR_ROUTE"
const val DETAILS_SCR_ROUTE = "DETAILS_SCR_ROUTE"

const val ARG_VIEWMODEL = "ARG_VIEWMODEL"
const val ARG_LIFECYCLEOWNER = "ARG_LIFECYCLEOWNER"
const val ARG_CONTEXT = "ARG_CONTEXT"
const val ARG_ITEMSITEM = "ARG_ITEMSITEM"